### ISSUE TITLE
css class fix

### ISSUE THREAD

**Issue by BraveButter** [Jxckaroo/serenity-gaming#37]
Hey, I saw your website and i guess there is a bug in your css class .white-section.
The games section is not centered on a monitor where the resolution is higher than 1080p.

.white-section {
    height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center; <-- add this to fix it
    background-color: lightgrey;
}

**Comment by Jxckaroo** [comment]
Hey,

Thanks my dude - i will release a fix for this!
